### PR TITLE
Updating from master to 24Jul17

### PR DESCRIPTION
**Pull request by stanmoore1**
@timattox can you run this through your testing? There were some merge conflicts that I fixed.

### CODE REVIEW

**Comment by stanmoore1** [comment]
@timattox I'm seeing a segfault in bench05 and a few others and will probably need your help to fix it:

<pre>
==27027== Invalid read of size 4
==27027==    at 0x709069: LAMMPS_NS::NPairHalfBinNewtonSSA::build(LAMMPS_NS::NeighList*) (npair_half_bin_newton_ssa.cpp:266)
==27027==    by 0x6EDD53: LAMMPS_NS::Neighbor::build(int) (neighbor.cpp:2126)
==27027==    by 0xAC5FC4: LAMMPS_NS::Verlet::run(int) (verlet.cpp:285)
==27027==    by 0xA92F30: LAMMPS_NS::Run::command(int, char**) (run.cpp:183)
==27027==    by 0x682105: void LAMMPS_NS::Input::command_creator<LAMMPS_NS::Run>(LAMMPS_NS::LAMMPS*, int, char**) (input.cpp:861)
==27027==    by 0x680576: LAMMPS_NS::Input::execute_command() (input.cpp:844)
==27027==    by 0x681AE6: LAMMPS_NS::Input::file() (input.cpp:244)
==27027==    by 0x693815: main (main.cpp:44)
==27027==  Address 0xd69dd14 is 14,116 bytes inside a block of size 15,396 free'd
==27027==    at 0x4A06430: free (vg_replace_malloc.c:446)
==27027==    by 0x6CF9A2: LAMMPS_NS::NBin::bin_atoms_setup(int) (memory.h:93)
==27027==    by 0x6EDCE3: LAMMPS_NS::Neighbor::build(int) (neighbor.cpp:2114)
==27027==    by 0xAC5FC4: LAMMPS_NS::Verlet::run(int) (verlet.cpp:285)
==27027==    by 0xA92F30: LAMMPS_NS::Run::command(int, char**) (run.cpp:183)
==27027==    by 0x682105: void LAMMPS_NS::Input::command_creator<LAMMPS_NS::Run>(LAMMPS_NS::LAMMPS*, int, char**) (input.cpp:861)
==27027==    by 0x680576: LAMMPS_NS::Input::execute_command() (input.cpp:844)
==27027==    by 0x681AE6: LAMMPS_NS::Input::file() (input.cpp:244)
==27027==    by 0x693815: main (main.cpp:44)
==27027==
</pre>

**Comment by timattox** [comment]
I'll try to have a look today, but it might be tomorrow before I get to it.

**Comment by stanmoore1** [comment]
@timattox sounds good. I fixed merge conflicts in `nbin_ssa.cpp` and `npair_half_bin_newton_ssa.cpp` related to `atom2bin` changes from Steve but must have introduced a bug at the same time.

**Comment by stanmoore1** [comment]
@timattox I resolved the merge conflict in 67a0183. Can you take a look? This change is safe since ssa neighborlists aren't used to build occasional lists, see https://github.com/lammps/lammps/issues/462. However, if they could be used for occasional lists, then the atom2bin change would need to be added.

**Comment by stanmoore1** [comment]
@timattox I tried to use the atom2bin change, but I was getting a segfault in the ssa neighborlist build. I think one would need to store xbin, ybin, and zbin as well as the bin id.

**Comment by stanmoore1** [comment]
I mean bin id, not atom id

**Comment by stanmoore1** [comment]
@timattox for more background on the atom2bin fix, see http://lammps.sandia.gov/bug.html, 19 May 2017, 

> Two neighbor list bug fixes, one for occasional lists that are not copies of a perpetual list due to them sometimes getting out-of-sync with binning of atoms."

**Pull request closed without merging**
