### PR TITLE
get PairTableKokkos to inherit from PairTable (also fix GPU)

### PR DESCRIPTION
**Pull request by ibaned**
see #5 for some rationale.
this PR also fixes GPU memory access bugs that were present
in the original PairTableKokkos.

@stanmoore1

### CODE REVIEW

**Comment by stanmoore1** [comment]
Nice

**Comment by stanmoore1** [comment]
@ibaned can you also submit a pull request for PairTableKokkos to master LAMMPS?

**Comment by ibaned** [comment]
I just rebased this branch onto master LAMMPS and submitted lammps/lammps#324. hopefully if they are the same commit hashes it will not be so bad to get it merged twice into the timeline.

**Comment by stanmoore1** [comment]
This pull request has already been merged into master. Closed #6.

**Pull request closed without merging**
