### PR TITLE
pair_table_rx_kokkos

### PR DESCRIPTION
**Pull request by ibaned**
This PR provides a Kokkos version of user-dpd's pair_table_rx. Due to the use of uCG and uCGnew variables, I don't use the pair_kokkos.h framework. Furthermore, due to increasing complications with lambdas, I do not copy the pair class itself to the device, but rather extract all necessary Kokkos Views and pass them to free functions. Finally, a couple things in the core of LAMMPS had to be made more visible so they could be used from free functions.

@stanmoore1

### CODE REVIEW

**Comment by ibaned** [comment]
This was tested with multiple threads with OpenMP, and gives the same results for DPD bench14. CUDA tests are promising, but will remain inconclusive until outstanding bugs in Kokkos pair_hybrid are fixed.

**Comment by stanmoore1** [comment]
@ibaned why not derive from PairTableRX instead of PairTable to avoid code duplication?

**Comment by ibaned** [comment]
I think the majority of the new code would still need to be different, but if its important I could try to do that...

**Comment by stanmoore1** [comment]
OK, this could be an optimization in the future, but probably not too important now.

**Pull request merged**
