### PR TITLE
Many CUDA runtime fixes

### PR DESCRIPTION
**Pull request by ibaned**
I've fixed several issues with CUDA lambdas and just plain accessing the wrong memory space. There are still more to go...

@stanmoore1

### CODE REVIEW

**Comment by stanmoore1** [comment]
Thanks @ibaned!

**Comment by stanmoore1** [comment]
@ibaned and @timattox we are getting regression test failures for OpenMP (the differences are fairly small but everything passed before this PR was merged). For example:

<pre>
==== comparing log.kk_omp_1_2.bench01 with log.02Mar17.linux.kk_omp_1_2.bench01 ====
Step     error  0.0 wrt norm     1.0
Temp     error 0.0315143357919 wrt norm     1.0
Press    error 0.0170131302487 wrt norm     1.0
Volume   error  0.0 wrt norm     1.0
PotEng   error 0.000388527243936 wrt norm     1.0
KinEng   error 0.0315143372332 wrt norm     1.0
c_dpdU[1]           error 2.38736288983e-18
c_dpdU[2]  error 0.00161666200273 wrt norm     1.0
v_totEnergy  error 3.48805260155e-08 wrt norm     1.0
Pxx      error 0.0270217233605 wrt norm     1.0
Pyy      error 0.0337889792238 wrt norm     1.0
Pzz      error 0.014829333609 wrt norm     1.0
Lx       error  0.0 wrt norm     1.0
Ly       error  0.0 wrt norm     1.0
Lz       error  0.0 wrt norm     1.0
!!! test bench01 FAILED
elapsed time = 5.94838809967 s for test bench01
</pre>

**Comment by stanmoore1** [comment]
886cc69dfba3fb227ce60f5493170fbd53e1afbc passed with no failures

**Comment by timattox** [comment]
I'll have a look at what could be causing the regression.  Thanks @ibaned for making these Kokkos fixes.

**Comment by timattox** [comment]
Hmmm, all my regression tests pass with 5b3101cb, but I am comparing against more recent captures of "known good" outputs from ed089c34.  That was the last change that should have re-arranged the order of random numbers used in the stochastic calculations.

**Comment by stanmoore1** [comment]
@timattox Yes, all is well. There was a recent change to non-Kokkos DPD and my "known good" files weren't updated, so that made it look like a regression when it wasn't.

**Comment by timattox** [comment]
I should have been a bit more precise... due to the use of a different random number generator, the stochastic forces will be different between a pure MPI run, and a Kokkos run, even if there is only 1 kokos thread per MPI rank.  If I had time, I would port the the RNG from Kokkos_Random.hpp to non-kokkos, so we could get the same stochastic forces regardless.  It could be made a drop-in replacement for random_mars... but alas, no time to do so.

**Pull request merged**
