### PR TITLE
Get PairTableRX to inherit from PairTable

### PR DESCRIPTION
**Pull request by ibaned**
This saves a lot of duplicate code, and uses newer functionality from PairTable.

@stanmoore1

### CODE REVIEW

**Comment by stanmoore1** [comment]
@timattox I think this PR is a good idea. The same change could be applied to other USER-DPD styles like pair_multi_lucy_rx to greatly reduce code duplication.

**Comment by stanmoore1** [comment]
@ibaned Can you revert moving the enum to pair.h in this PR and the one to master? I talked to Steve and he thought that was the best solution for the short term. The issue is that there could be name collisions, especially if the constants are in pair.h which is referenced by basically every pair style in LAMMPS.

**Comment by ibaned** [comment]
okay, rebased again as well. #5, #6, and lammps/lammps#324 should have the enums back where they belong.

**Comment by stanmoore1** [comment]
Thanks Dan!

**Comment by stanmoore1** [comment]
Tim, I think this would be good to cherry pick back to Master, do you agree?

**Comment by timattox** [comment]
Yes, I agree, this owuld be good to push to master.
I also think something similar for pair_multi_lucy and pair_multi_lucy_rx could be done.
I just sent you and Dan an e-mail about that.

**Comment by ibaned** [comment]
apparently pair_table_rx changed between LAMMPS master and USER-DPD_kokkos, prior to my changes, which makes it non-trivial to make this a direct PR to master.

**Comment by timattox** [comment]
yeah... pull request [LAMMPS#306](https://github.com/lammps/lammps/pull/306) was the source of those changes. Sorry.

**Comment by timattox** [comment]
Unless others see a reason to push it over to master earlier, I think this can wait until we merge the whole USER-DPD_kokkos branch back to master...

**Pull request merged**
